{% set name = "sdl_image" %}
{% set version = "1.2.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://www.libsdl.org/projects/SDL_image/release/SDL_image-{{ version }}.tar.gz
    sha256: 0b90722984561004de84847744d566809dbb9daf732a9e503b91a1b5a84e5699
  - path: cmake/

build:
  number: 7
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake  # [win]
    - ninja  # [win]
    - make   # [unix]
    - gnuconfig   # [unix]
  host:
    - sdl
    - libtiff
    - libpng
    - zlib
    - libjpeg-turbo
    - libwebp
  run:
    - sdl
    - libtiff
    - libpng
    - zlib
    - libjpeg-turbo
    - libwebp

test:
  commands:
    - test -f ${PREFIX}/include/SDL/SDL_image.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\SDL\\SDL_image.h exit 1  # [win]

about:
  home: https://www.libsdl.org/index.php
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: |
    SDL_image is an image file loading library with Simple DirectMedia Layer

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
    - Tobias-Fischer
